# Generated by Django 5.2.1 on 2025-09-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromUnit', models.CharField(max_length=255)),
                ('toUnit', models.CharField(max_length=255)),
                ('unitAmount', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
    ]
